language: node_js
sudo: false
script:
- echo "no build step yet"
node_js:
- 4.2.4
before_deploy:
- npm install json
- node_modules/.bin/json -E "this.version='$TRAVIS_TAG'" -f package.json -I
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: npm
  email: JanS@DracoBlue.de
  api_key:
    secure: W2oCA2WB6xZ1K4US9wp0CQoCh49orwtu9PklmXr5H36i6KeBNeMtwPAxM2X22GlYGVi00iezxN8S46dnRQtjq486ZPtrqya9OmQKcz7k/5qDbBLpVoxsaAMM7n+vxiU8hnSe7V4Q6F28yhbmL5EPv8r0HP6JYQHLOPVEFLN0iV0=
  on:
    tags: true
    repo: nikita-kit/nikita-css
    all_branches: true
    node: 4.2.4
